"""initial schema

Revision ID: 813fa6ba88d2
Revises: 
Create Date: 2026-04-29 06:38:24.820983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813fa6ba88d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_country',
    sa.Column('country_key', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=False),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=False),
    sa.Column('iso_numeric', sa.SmallInteger(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('sub_region', sa.String(length=50), nullable=True),
    sa.Column('continent', sa.String(length=20), nullable=True),
    sa.Column('income_group', sa.String(length=30), nullable=True),
    sa.Column('is_landlocked', sa.Boolean(), nullable=True),
    sa.Column('primary_currency_code', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('country_key'),
    sa.UniqueConstraint('iso_numeric'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_dim_country_iso_alpha_2'), 'dim_country', ['iso_alpha_2'], unique=True, schema='dw')
    op.create_index(op.f('ix_dw_dim_country_iso_alpha_3'), 'dim_country', ['iso_alpha_3'], unique=True, schema='dw')
    op.create_index(op.f('ix_dw_dim_country_region'), 'dim_country', ['region'], unique=False, schema='dw')
    op.create_table('dim_currency',
    sa.Column('currency_key', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('decimal_places', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('currency_key'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_dim_currency_currency_code'), 'dim_currency', ['currency_code'], unique=True, schema='dw')
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('day_name', sa.String(length=10), nullable=False),
    sa.Column('week_of_year', sa.SmallInteger(), nullable=False),
    sa.Column('month_num', sa.SmallInteger(), nullable=False),
    sa.Column('month_name', sa.String(length=10), nullable=False),
    sa.Column('quarter_num', sa.SmallInteger(), nullable=False),
    sa.Column('calendar_year', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_year_in', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_quarter_in', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_month_in', sa.SmallInteger(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.Column('is_quarter_end', sa.Boolean(), nullable=False),
    sa.Column('is_fiscal_year_end_in', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_dim_date_calendar_year'), 'dim_date', ['calendar_year'], unique=False, schema='dw')
    op.create_index(op.f('ix_dw_dim_date_fiscal_year_in'), 'dim_date', ['fiscal_year_in'], unique=False, schema='dw')
    op.create_index(op.f('ix_dw_dim_date_full_date'), 'dim_date', ['full_date'], unique=False, schema='dw')
    op.create_table('dim_hs_code',
    sa.Column('hs_code_key', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('hs_code', sa.String(length=8), nullable=False),
    sa.Column('hs_level', sa.SmallInteger(), nullable=False),
    sa.Column('hs_2', sa.String(length=2), nullable=False),
    sa.Column('hs_4', sa.String(length=4), nullable=True),
    sa.Column('hs_6', sa.String(length=6), nullable=True),
    sa.Column('hs_version', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('section_code', sa.String(length=5), nullable=True),
    sa.Column('section_name', sa.String(length=200), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('hs_code_key'),
    sa.UniqueConstraint('hs_code', 'hs_version', name='uq_hs_code_version'),
    schema='dw'
    )
    op.create_index('idx_hs_h2', 'dim_hs_code', ['hs_2'], unique=False, schema='dw')
    op.create_index('idx_hs_h4', 'dim_hs_code', ['hs_4'], unique=False, schema='dw')
    op.create_index(op.f('ix_dw_dim_hs_code_hs_code'), 'dim_hs_code', ['hs_code'], unique=False, schema='dw')
    op.create_table('dim_macro_indicator',
    sa.Column('indicator_key', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('indicator_key'),
    sa.UniqueConstraint('indicator_code'),
    schema='dw'
    )
    op.create_table('dim_state',
    sa.Column('state_key', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('is_union_territory', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('capital', sa.String(length=50), nullable=True),
    sa.Column('is_coastal', sa.Boolean(), nullable=True),
    sa.Column('population_latest', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('state_key'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_dim_state_state_code'), 'dim_state', ['state_code'], unique=True, schema='dw')
    op.create_table('ingestion_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ops'
    )
    op.create_index(op.f('ix_ops_ingestion_log_source'), 'ingestion_log', ['source'], unique=False, schema='ops')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ops'
    )
    op.create_index(op.f('ix_ops_users_email'), 'users', ['email'], unique=True, schema='ops')
    op.create_table('fact_currency_rate',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('base_currency_key', sa.BigInteger(), nullable=False),
    sa.Column('quote_currency_key', sa.BigInteger(), nullable=False),
    sa.Column('mid_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_key'], ['dw.dim_currency.currency_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dw.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['quote_currency_key'], ['dw.dim_currency.currency_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key', 'base_currency_key', 'quote_currency_key', 'source_system', name='uq_fx_rate'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_fact_currency_rate_date_key'), 'fact_currency_rate', ['date_key'], unique=False, schema='dw')
    op.create_table('fact_macro_indicator',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('country_key', sa.BigInteger(), nullable=False),
    sa.Column('indicator_key', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_key'], ['dw.dim_country.country_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dw.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['indicator_key'], ['dw.dim_macro_indicator.indicator_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key', 'country_key', 'indicator_key', 'source_system', name='uq_macro_ind'),
    schema='dw'
    )
    op.create_index(op.f('ix_dw_fact_macro_indicator_country_key'), 'fact_macro_indicator', ['country_key'], unique=False, schema='dw')
    op.create_index(op.f('ix_dw_fact_macro_indicator_date_key'), 'fact_macro_indicator', ['date_key'], unique=False, schema='dw')
    op.create_table('fact_trade_monthly',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('hs_code_key', sa.BigInteger(), nullable=False),
    sa.Column('country_key', sa.BigInteger(), nullable=False),
    sa.Column('state_key', sa.BigInteger(), nullable=True),
    sa.Column('value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('n_shipments', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('extract_date_key', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_key'], ['dw.dim_country.country_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dw.dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['hs_code_key'], ['dw.dim_hs_code.hs_code_key'], ),
    sa.ForeignKeyConstraint(['state_key'], ['dw.dim_state.state_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key', 'direction', 'hs_code_key', 'country_key', 'source_system', name='uq_trade_monthly'),
    schema='dw'
    )
    op.create_index('idx_tradem_country', 'fact_trade_monthly', ['country_key'], unique=False, schema='dw')
    op.create_index('idx_tradem_date', 'fact_trade_monthly', ['date_key'], unique=False, schema='dw')
    op.create_index('idx_tradem_direction', 'fact_trade_monthly', ['direction'], unique=False, schema='dw')
    op.create_index('idx_tradem_hs', 'fact_trade_monthly', ['hs_code_key'], unique=False, schema='dw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tradem_hs', table_name='fact_trade_monthly', schema='dw')
    op.drop_index('idx_tradem_direction', table_name='fact_trade_monthly', schema='dw')
    op.drop_index('idx_tradem_date', table_name='fact_trade_monthly', schema='dw')
    op.drop_index('idx_tradem_country', table_name='fact_trade_monthly', schema='dw')
    op.drop_table('fact_trade_monthly', schema='dw')
    op.drop_index(op.f('ix_dw_fact_macro_indicator_date_key'), table_name='fact_macro_indicator', schema='dw')
    op.drop_index(op.f('ix_dw_fact_macro_indicator_country_key'), table_name='fact_macro_indicator', schema='dw')
    op.drop_table('fact_macro_indicator', schema='dw')
    op.drop_index(op.f('ix_dw_fact_currency_rate_date_key'), table_name='fact_currency_rate', schema='dw')
    op.drop_table('fact_currency_rate', schema='dw')
    op.drop_index(op.f('ix_ops_users_email'), table_name='users', schema='ops')
    op.drop_table('users', schema='ops')
    op.drop_index(op.f('ix_ops_ingestion_log_source'), table_name='ingestion_log', schema='ops')
    op.drop_table('ingestion_log', schema='ops')
    op.drop_index(op.f('ix_dw_dim_state_state_code'), table_name='dim_state', schema='dw')
    op.drop_table('dim_state', schema='dw')
    op.drop_table('dim_macro_indicator', schema='dw')
    op.drop_index(op.f('ix_dw_dim_hs_code_hs_code'), table_name='dim_hs_code', schema='dw')
    op.drop_index('idx_hs_h4', table_name='dim_hs_code', schema='dw')
    op.drop_index('idx_hs_h2', table_name='dim_hs_code', schema='dw')
    op.drop_table('dim_hs_code', schema='dw')
    op.drop_index(op.f('ix_dw_dim_date_full_date'), table_name='dim_date', schema='dw')
    op.drop_index(op.f('ix_dw_dim_date_fiscal_year_in'), table_name='dim_date', schema='dw')
    op.drop_index(op.f('ix_dw_dim_date_calendar_year'), table_name='dim_date', schema='dw')
    op.drop_table('dim_date', schema='dw')
    op.drop_index(op.f('ix_dw_dim_currency_currency_code'), table_name='dim_currency', schema='dw')
    op.drop_table('dim_currency', schema='dw')
    op.drop_index(op.f('ix_dw_dim_country_region'), table_name='dim_country', schema='dw')
    op.drop_index(op.f('ix_dw_dim_country_iso_alpha_3'), table_name='dim_country', schema='dw')
    op.drop_index(op.f('ix_dw_dim_country_iso_alpha_2'), table_name='dim_country', schema='dw')
    op.drop_table('dim_country', schema='dw')
    # ### end Alembic commands ###
